Feat/quiz
gdsc-hcmut/ctct-be pull request #12
Opened 2023-07-28 01:25 UTC by qhung312

2023-07-30 03:06 UTC, lygioian requested changes

2023-07-30 03:06 UTC, lygioian commented on src/services/material.service.ts
> +        return (
ko return await

2023-07-30 03:06 UTC, lygioian commented on src/services/question_template.service.ts
> +    attachUserAnswerToQuestion(question: ConcreteQuestion, answers: any[]) {
ko dùng any

2023-07-30 03:06 UTC, lygioian commented on src/services/cache.service.ts
>          options: any = {}
ko any

2023-07-30 03:06 UTC, lygioian commented on src/services/question_template.service.ts
>      async create(userId: Types.ObjectId, data: any) {
ko any

2023-07-30 03:06 UTC, lygioian commented on src/services/quiz_template.service.ts
>      async create(userId: Types.ObjectId, data: any) {
ko any

2023-07-30 03:06 UTC, lygioian commented on src/services/task-scheduling/task_scheduling.service.ts
> +    async cancel(query: any) {
ko any

2023-07-30 03:06 UTC, lygioian commented on src/services/task-scheduling/task_scheduling.service.ts
> +    async disable(query: any) {
no any

2023-07-31 11:06 UTC, qhung312 commented on src/controllers/access_level.controller.ts
> +            const { description = "" } = req.body;
em đã fix r nha

2023-08-02 08:14 UTC, lygioian approved these changes

2023-08-02 09:57 UTC, merged