Feat/news
gdsc-hcmut/ctct-be pull request #79
Opened 2024-03-25 16:00 UTC by dvtdat

2024-03-27 14:41 UTC, qhung312 approved these changes

2024-03-27 14:49 UTC, qhung312 requested changes

2024-03-27 14:49 UTC, qhung312 commented on src/controllers/admin/news.controller.ts
> +            if (_.isEmpty(newsInfo.title)) {
em nhận thumbnail là string, v e định handle chuyện upload thumbnail ntn v

2024-03-27 14:49 UTC, qhung312 commented on src/services/news.service.ts
> +    }
sao censor mà a thấy em pick hết field luôn v

2024-03-27 14:49 UTC, qhung312 commented on src/services/news.service.ts
> +
có deletedAt thì arg đầu tiên của findOne phải là {...query, deletedAt: { $exists: false }} chứ?

2024-03-27 14:49 UTC, qhung312 commented on src/services/news.service.ts
> +
check thêm deletedAt k tồn tại

2024-04-02 13:37 UTC, dvtdat commented on src/controllers/admin/news.controller.ts
> +            if (_.isEmpty(newsInfo.title)) {
Dạ chỗ này thì do em chưa học cách setup để upload ảnh lên cloud nên em để string để admin paste link imgur (hoặc các platform upload ảnh tương tự) để render ảnh từ link đó. Nếu phần này cần upload ảnh lên cloud luôn thì để em nghiên cứu cách thức phù hợp.

2024-04-02 13:45 UTC, dvtdat commented on src/services/news.service.ts
> +    }
dạ model NewsDocument ngoài những cái trên ra thì còn có "createdBy: User" với "deletedAt" nữa ấy, những cái đó là phần em censor

2024-04-22 15:34 UTC, qhung312 approved these changes

2024-04-22 15:38 UTC, merged